spring: 
  application:
    name: mizu-note
  datasource:
#    url: jdbc:mysql://localhost:3306/mizunote
    url: jdbc:h2:~/mizunotedb
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
