spring: 
  application:
    name: mizu-note
  datasource:
    url: jdbc:mysql://localhost:3306/mizunote
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true
