CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'ユーザID',
    email VARCHAR(255) NOT NULL UNIQUE COMMENT 'メールアドレス',
    password VARCHAR(255) NOT NULL COMMENT 'パスワード',
    max_water_usage INT NOT NULL COMMENT '取水量上限 (単位: リットル)',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    deleted_flag BOOLEAN DEFAULT FALSE COMMENT '削除フラグ'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ユーザテーブル';

CREATE TABLE water_usage (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '取水量ID',
    user_id INT NOT NULL COMMENT 'ユーザID (外部キー: user.id)',
    water_amount INT NOT NULL COMMENT '取水量 (単位: リットル)',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    deleted_flag BOOLEAN DEFAULT FALSE COMMENT '削除フラグ',
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='取水量テーブル';